[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.10.0"
edition = "2021"
rust-version = "1.76"
authors = ["Zenith Contributors"]
homepage = "https://github.com/init4tt/zenith"
repository = "https://github.com/init4tt/zenith"
license = "AGPL-3.0"

[workspace.dependencies]
alloy-primitives = { version = "=0.8.8", features = ["serde", "tiny-keccak"] }
alloy-sol-types = { version = "=0.8.8", features = ["json"] }

alloy-rlp = { version = "0.3.4" }

alloy = { version = "=0.5.2", features = ["full", "json-rpc", "signer-aws"] }
alloy-contract = { version = "=0.5.2", features = ["pubsub"] }

aws-config = "1.1.7"
aws-sdk-kms = "1.15.0"

hex = { package = "const-hex", version = "1", default-features = false, features = [
    "alloc",
] }
serde = { version = "1.0.197", features = ["derive"] }
tracing = "0.1.40"

zenith-types = { path = "crates/types" }
