[workspace]
members = [ "crates/*" ]
resolver = "2"

[workspace.package]
version = "0.7.1"
edition = "2021"
rust-version = "1.76"
authors = ["Zenith Contributors"]
homepage = "https://github.com/init4tt/zenith"
repository = "https://github.com/init4tt/zenith"
license = "AGPL-3.0"

[workspace.dependencies]
alloy-primitives = { version = "0.8", features = ["serde", "tiny-keccak"] }
alloy-sol-types = { version = "0.8", features = ["json"] }
alloy-rlp = { version = "0.3.4" }

alloy-contract = { version = "0.3", default-features = false }
alloy-consensus = { version = "0.3", default-features = false, features = ["k256", "kzg"] }
alloy-eips = { version = "0.3", default-features = false}
alloy-json-rpc = { version = "0.3", default-features = false }
alloy-network = { version = "0.3", default-features = false }
alloy-node-bindings = { version = "0.3", default-features = false }
alloy-provider = { version = "0.3", default-features = false, features = ["ws"] }
alloy-rpc-types = { version = "0.3", default-features = false }
alloy-rpc-types-eth = { version = "0.3", default-features = false }
alloy-rpc-client = { version = "0.3", default-features = false }
alloy-signer = { version = "0.3", default-features = false }
alloy-signer-local = { version = "0.3", default-features = false }
alloy-signer-aws = { version = "0.3", default-features = false }
alloy-transport = { version = "0.3", default-features = false }
alloy-transport-http = { version = "0.3", default-features = false }

aws-config = "1.1.7"
aws-sdk-kms = "1.15.0"

hex = { package = "const-hex", version = "1", default-features = false, features = ["alloc"] }
serde = { version = "1.0.197", features = ["derive"] }
tracing = "0.1.40"

zenith-types = { path = "crates/types" }