name: Docker ECR Push

on:
  push:
    branches: [main]


permissions:
  packages: write
  contents: read
  id-token: write

# simplest example of using the rust-base action
jobs:
  docker-ecr-push:
    uses: init4tech/actions/.github/workflows/ecr-build-and-push.yml@main
    with:
      rust-binary-name: zenith-builder-example
      environment: dev
    secrets:
      aws-ecr-repository: ${{ secrets.AWS_ECR_REPOSITORY }}
      aws-eks-cluster: ${{ secrets.AWS_EKS_CLUSTER }}
      aws-ecr-deployer-role-arn: ${{ secrets.AWS_ECR_DEPLOYER_ROLE_ARN }}
