name: Rust CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

# simplest example of using the rust-base action
jobs:
  rust-base:
    uses: init4tech/actions/.github/workflows/rust-library-base.yml@main
